import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '../styles/Home.module.css';

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div>
				<h1>Vision Verse Soundz</h1>
				<p>
					Lorem ipsum dolor sit, amet consectetur adipisicing elit. Perspiciatis
					impedit, incidunt doloribus distinctio nostrum ea vitae tenetur natus iure
					dignissimos animi aspernatur blanditiis cum atque quas ipsam facere
					necessitatibus illum.
				</p>
			</div>
		</>
	);
}
